version: '3'
services:
  mad-chatter:
    image: callmeamps/mad-chatter:arm64v8-0.0.3
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAINLIT_HOST=${CHAINLIT_HOST}
      - CHAINLIT_PORT=${CHAINLIT_PORT}
      - CHAINLIT_CLOUD_ID=${CHAINLIT_CLOUD_ID}
    ports:
      - 36789:8080
    volumes:
      - ./data:/madchatter/data
